apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: test-k8s-zzy
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: test-k8s-zzy
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: test-k8s-zzy
    spec:
      # 定义容器，可以多个
      containers:
      - name: test-k8s-zzy # 容器名字
        image: azhang41/test:v1 # 镜像
